from dataclasses import dataclass, field
from typing import Any, Union

from releaseguard_agent.tools.base import ToolResult


@dataclass(frozen=True)
class AgentTextEvent:
    """Incremental text output generated by the LLM."""

    delta: str


@dataclass(frozen=True)
class AgentThinkingEvent:
    """Incremental reasoning / thinking trace generated by the LLM."""

    thinking: str


@dataclass(frozen=True)
class AgentToolUseEvent:
    """Tool invocation emitted by the LLM."""

    tool_id: str
    tool_name: str
    arguments: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AgentToolResultEvent:
    """Result of a dispatched tool invocation."""

    tool_id: str
    tool_name: str
    result: ToolResult
    duration_ms: float = 0.0


@dataclass(frozen=True)
class AgentTurnCompleteEvent:
    """Signals that one turn of ReAct thinking and tool execution has finished."""

    turn: int


@dataclass(frozen=True)
class AgentLoopCompleteEvent:
    """Signals that the full multi-turn ReAct loop has terminated."""

    total_turns: int
    final_content: str = ""


@dataclass(frozen=True)
class AgentErrorEvent:
    """Signals an error or abort condition during the ReAct loop."""

    error: str


AgentEvent = Union[
    AgentTextEvent,
    AgentThinkingEvent,
    AgentToolUseEvent,
    AgentToolResultEvent,
    AgentTurnCompleteEvent,
    AgentLoopCompleteEvent,
    AgentErrorEvent,
]
